spring:
  sql:
    init:
      mode: never
      encoding: UTF-8
  ai:
    vectorstore:
      milvus:
        initialize-schema: true

logging:
  level:
    org.springframework.ai.openai: DEBUG
    org.springframework.ai.chat.client: DEBUG
    com.unbags.ordering.ai: DEBUG
